/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GeoVoteFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLandmark"
      | "admin"
      | "confidentialProtocolId"
      | "getLandmark"
      | "getLandmarkCount"
      | "getVotesHandle"
      | "grantViewVotes"
      | "hasVoted"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LandmarkAdded" | "ViewerGranted" | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLandmark",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLandmark",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLandmarkCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVotesHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantViewVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLandmark",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLandmark",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLandmarkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotesHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantViewVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace LandmarkAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    country: string,
    imageUrl: string,
    latMicro: BigNumberish,
    lngMicro: BigNumberish,
    addedBy: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    country: string,
    imageUrl: string,
    latMicro: bigint,
    lngMicro: bigint,
    addedBy: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    country: string;
    imageUrl: string;
    latMicro: bigint;
    lngMicro: bigint;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViewerGrantedEvent {
  export type InputTuple = [id: BigNumberish, viewer: AddressLike];
  export type OutputTuple = [id: bigint, viewer: string];
  export interface OutputObject {
    id: bigint;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    id: BigNumberish,
    voter: AddressLike,
    votesAfter: BigNumberish
  ];
  export type OutputTuple = [id: bigint, voter: string, votesAfter: bigint];
  export interface OutputObject {
    id: bigint;
    voter: string;
    votesAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GeoVoteFHE extends BaseContract {
  connect(runner?: ContractRunner | null): GeoVoteFHE;
  waitForDeployment(): Promise<this>;

  interface: GeoVoteFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLandmark: TypedContractMethod<
    [
      name: string,
      country: string,
      imageUrl: string,
      latMicro: BigNumberish,
      lngMicro: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getLandmark: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        country: string;
        imageUrl: string;
        latMicro: bigint;
        lngMicro: bigint;
        votes: bigint;
      }
    ],
    "view"
  >;

  getLandmarkCount: TypedContractMethod<[], [bigint], "view">;

  getVotesHandle: TypedContractMethod<[id: BigNumberish], [string], "view">;

  grantViewVotes: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  hasVoted: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  vote: TypedContractMethod<
    [id: BigNumberish, encOne: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLandmark"
  ): TypedContractMethod<
    [
      name: string,
      country: string,
      imageUrl: string,
      latMicro: BigNumberish,
      lngMicro: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLandmark"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        country: string;
        imageUrl: string;
        latMicro: bigint;
        lngMicro: bigint;
        votes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLandmarkCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVotesHandle"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantViewVotes"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [id: BigNumberish, encOne: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LandmarkAdded"
  ): TypedContractEvent<
    LandmarkAddedEvent.InputTuple,
    LandmarkAddedEvent.OutputTuple,
    LandmarkAddedEvent.OutputObject
  >;
  getEvent(
    key: "ViewerGranted"
  ): TypedContractEvent<
    ViewerGrantedEvent.InputTuple,
    ViewerGrantedEvent.OutputTuple,
    ViewerGrantedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "LandmarkAdded(uint256,string,string,string,int64,int64,address)": TypedContractEvent<
      LandmarkAddedEvent.InputTuple,
      LandmarkAddedEvent.OutputTuple,
      LandmarkAddedEvent.OutputObject
    >;
    LandmarkAdded: TypedContractEvent<
      LandmarkAddedEvent.InputTuple,
      LandmarkAddedEvent.OutputTuple,
      LandmarkAddedEvent.OutputObject
    >;

    "ViewerGranted(uint256,address)": TypedContractEvent<
      ViewerGrantedEvent.InputTuple,
      ViewerGrantedEvent.OutputTuple,
      ViewerGrantedEvent.OutputObject
    >;
    ViewerGranted: TypedContractEvent<
      ViewerGrantedEvent.InputTuple,
      ViewerGrantedEvent.OutputTuple,
      ViewerGrantedEvent.OutputObject
    >;

    "Voted(uint256,address,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
